### ISSUE TITLE
When department isn't in shiftly, the user home screen doesn't load

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/stat-engine#136]

**Comment by chopchop505** [comment]
Actually I think think when the department has no data in es index, it fails.  Not related to shiftly.  Need to confirm

**Comment by chopchop505** [comment]
```
[statengine-statengine-7f4457b765-rqrhl] TypeError: Cannot read property 'start' of undefined 
[statengine-statengine-7f4457b765-rqrhl] at calculateTimeRange (/usr/src/stat-engine/dist/server/lib/timeRangeUtils.js:45:34) 
[statengine-statengine-7f4457b765-rqrhl] at getTopIncidents (/usr/src/stat-engine/dist/server/api/incident/incident.controller.js:67:58) 
[statengine-statengine-7f4457b765-m5qcf] TypeError: Cannot read property 'start' of undefined 
[statengine-statengine-7f4457b765-m5qcf] at calculateTimeRange (/usr/src/stat-engine/dist/server/lib/timeRangeUtils.js:45:34) 
[statengine-statengine-7f4457b765-rqrhl] at Layer.handle [as handle_request] (/usr/src/stat-engine/node_modules/express/lib/router/layer.js:95:5) 
[statengine-statengine-7f4457b765-m5qcf] at getStats (/usr/src/stat-engine/dist/server/api/stats/stats.controller.js:21:58) 
```

**Comment by chopchop505** [comment]
Nevermind...pushed a fix
